/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appointmentcalendar;
import java.util.Scanner;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class accountLoginGUI extends javax.swing.JFrame {

    static final String JDBC_DRIVER = "org.apache.derby.jdbc.ClientDriver";
    static final String DB_URL = "jdbc:derby://localhost:1527/343Project1testdb";

  //  Database credentials
    static final String USER = "newuser";
    static final String PASS = "newpass";
    public Connection conn;
    public Statement stmt; 
    /**
     * Creates new form accountLogin
     */
    public accountLoginGUI()
    {
        initComponents();
        setSize(720,480);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        theAppointmentSchedulerTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        createNewAccountButton = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JButton();
        changeUserPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        theAppointmentSchedulerTitle.setFont(new java.awt.Font("Copperplate", 0, 24)); // NOI18N
        theAppointmentSchedulerTitle.setForeground(new java.awt.Color(255, 255, 255));
        theAppointmentSchedulerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        theAppointmentSchedulerTitle.setText("THE APPOINTMENT SCHEDULER");
        getContentPane().add(theAppointmentSchedulerTitle);
        theAppointmentSchedulerTitle.setBounds(135, 18, 405, 58);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMAIL ADDRESS");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(147, 82, 110, 16);

        emailText.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(emailText);
        emailText.setBounds(147, 104, 357, 24);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 150, 69, 16);

        exitButton.setBackground(new java.awt.Color(255, 255, 0));
        exitButton.setForeground(new java.awt.Color(255, 0, 51));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(450, 300, 78, 32);

        createNewAccountButton.setBackground(new java.awt.Color(255, 255, 0));
        createNewAccountButton.setForeground(new java.awt.Color(255, 0, 51));
        createNewAccountButton.setText("CREATE A NEW ACCOUNT");
        createNewAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createNewAccountButton);
        createNewAccountButton.setBounds(90, 300, 191, 32);
        getContentPane().add(passwordText);
        passwordText.setBounds(150, 180, 350, 22);

        signInButton.setBackground(new java.awt.Color(255, 255, 51));
        signInButton.setForeground(new java.awt.Color(204, 0, 51));
        signInButton.setText("SIGN IN");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signInButton);
        signInButton.setBounds(330, 300, 78, 32);

        changeUserPass.setBackground(new java.awt.Color(255, 255, 51));
        changeUserPass.setForeground(new java.awt.Color(204, 0, 51));
        changeUserPass.setText("CHANGE EMAIL ADDRESS/PASSWORD");
        changeUserPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserPassActionPerformed(evt);
            }
        });
        getContentPane().add(changeUserPass);
        changeUserPass.setBounds(190, 230, 280, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void systemExit()
    {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }
    
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void createNewAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccountButtonActionPerformed
            systemExit();
            accountCreatorGUI creator = new accountCreatorGUI();
            creator.setVisible(true);
    }//GEN-LAST:event_createNewAccountButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        
        try{
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            String sql = "SELECT * FROM Patients WHERE pEmail = ? AND password = ?";
            PreparedStatement statement = conn.prepareStatement(sql);
            
            statement.clearParameters();
            statement.setString(1,emailText.getText());
            statement.setString(2,passwordText.getText());
            ResultSet rs = statement.executeQuery();
            
            if(rs.next())
            {
                JOptionPane.showMessageDialog(null, "Sign In Successful!");
                systemExit();
                CalendarGUI calendar = new CalendarGUI();
                calendar.setVisible(true);
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Invalid Sign-In Information! Try Again");
                emailText.setText("");
                passwordText.setText("");
            }
            conn.close();
      
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }    
        
    }//GEN-LAST:event_signInButtonActionPerformed

    private void changeUserPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserPassActionPerformed
        systemExit();
        accountChanger change = new accountChanger();
        change.setVisible(true);
    }//GEN-LAST:event_changeUserPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeUserPass;
    private javax.swing.JButton createNewAccountButton;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel theAppointmentSchedulerTitle;
    // End of variables declaration//GEN-END:variables
}
